### ISSUE TITLE
Garbage collector error

### ISSUE THREAD

**Issue by gitarns** [enix/kube-image-keeper#128]
Hello,

We face a problem with the garbage collector which prevents the registry to start:

Log of the GC container:
failed to garbage collect: failed to mark: filesystem: filesystem: failed to retrieve tags unknown repository name=xxxxx

The failling GC container prevents the registry container to start.

**Comment by paullaffitte** [comment]
related to #120

**Comment by donch** [comment]
Hi @gitarns , we merged https://github.com/enix/kube-image-keeper/pull/120 , would you mind trying with the version 1.3.0-beta.2, please?
