### ISSUE TITLE
Error while proxying to origin for image with dash

### ISSUE THREAD

**Issue by Tefnet** [enix/kube-image-keeper#134]
For ECR image name with dash in hostname part, for example
"541517799999.dkr.ecr.us-east-2.amazonaws.com/foo/bar:tag"

proxy fails with error:

I0726 20:43:12.023260       1 server.go:138] "proxying request" repository="foo/bar" originRegistry="541517799999.dkr.ecr.us-east:2.amazonaws.com"
I0726 20:43:12.281235       1 server.go:141] "cached image is not available, proxying origin" originRegistry="541517799999.dkr.ecr.us-east:2.amazonaws.com" error="307 Temporary Redirect"

It breaks hostname part
541517799999.dkr.ecr.us-east:2.amazonaws.com
it should be
541517799999.dkr.ecr.us-east-2.amazonaws.com

Tested on 1.3.0-beta.1

**Comment by donch** [comment]
Hi @Tefnet , thanks your for raising this bug.
I am able to reproduce the bug. Even though the controller is able to cache the image so that the pod can be correctly scheduled afterwards, we will shortly fix this bug !
