### ISSUE TITLE
What is kuik pod finalizer function?

### ISSUE THREAD

**Issue by sleterrier** [enix/kube-image-keeper#135]
Hi,

Finalizers on pods sound a bit scary from an operational standpoint, as they could prevent (very) large number of pods to get terminated in the event of the underlying controller being unavailable or removed.
While considering kube-image-keeper for our production environments, I was hoping you could shed some light on the function of `pod.kuik.enix.io/finalizer` in kuik architecture.

Thanks again for sharing and maintaining this very promising project!

**Comment by Nicolasgouze** [comment]
Hi @sleterrier , sorry for closing quickly this ticket. 
As an explanation : see #136, we optimized kuik call-flows & robustness by removing finalizers.
