### ISSUE TITLE
Caching the latest docker images for a deployment without expiry?

### ISSUE THREAD

**Issue by jperville** [enix/kube-image-keeper#154]
Hello enix,

We are considering using kuik to keep docker images used in a customer environment available even if the docker images are pruned from our own registry in the future. Kuik would allow the customer to keep running its old applications regardless of our image pruning policy.

Currently, kuik works very well when deployments have >0 replicas:
 - every docker image from our docker registry is cached by kuik as soon as the first pod uses it
 - the cached docker images are not expiring (according to `kubectl get cachedimage`s) because at least 1 pod is using it

Now let's pretend that customer scales a deployment to 0 replicas, then goes to sleep for 6 months.
At some point, the docker image used by the customer is pruned from our registry, and is expired from kuik because:
 - no pod was using it, so the cachedimage has an expiration timestamp
 - the kuik garbage collector has ran and pruned the tag from the registry (because timestamp expired)

Now the customer wants to scale its deployment back to >0 replicas, but the image is gone both from our registry and from kuik. What can we do?

My naive idea was that maybe kuik could be configured to cache the docker images associated with the last N replicasets of the deployment without timestamp, even if the replicaset is scaled to 0 replicas.

What would be your thoughts about it?

**Comment by rdegez** [comment]
Hi!

That's indeed an interesting issue and we will brainstorm a bit to find an elegant solution to this problem.

In the meantime, maybe just increasing the [cachedImagesExpiryDelay](https://github.com/enix/kube-image-keeper/blob/main/helm/kube-image-keeper/values.yaml#L6) from the default 30d to say 180d or more could do the trick, assuming disk-space is not much of an issue :-)

Cheers,

**Comment by jperville** [comment]
I have another example in mind... How about if we patch a deployment which is scaled to 0 replicas to alter the image, how could we cache the docker images referenced in the latest replicaset of the deployment even if it was never scaled to > 0 replicas (and never hit the image proxy on the local host).

**Comment by Nicolasgouze** [comment]
Hello @jperville , 
Your first scenario should be now covered with the v1.4.0 release & more specifically this commit : https://github.com/enix/kube-image-keeper/commit/5129d19228bfcc2b6f66bf7ec4028f5bf0a198ea
Not 100% sure I understood correctly the 2nd scenario. Anyway, as it deals with other topics/features (potentially cache "pre-heating" / mutable tags / others) it should be tracked with an other ticket.
