### ISSUE TITLE
Upgrading from version 1.2 to 1.3 makes Pods stuck on Terminating

### ISSUE THREAD

**Issue by guy-frontegg** [enix/kube-image-keeper#183]
Hey All,

I want to start by saying that we really like this Kuik solution and think you are doing a great job.

Yesterday we upgraded to version 1.3 and started noticing pods that were being deleted are stuck on terminating.

After a little bit of code digging, we noticed that the finalizer was removed from version 1.3. This of course makes the terminating pods stuck since no one is handling the finalizers anymore.

So we delete all the finalizers from old pods, but I think you need to add a migration part in the documentation and maybe bump the version to 2 since there are breaking changes

Thank you

(Or maybe we are completely wrong and missed something)

**Comment by Nicolasgouze** [comment]
Hi @guy-frontegg , Thanks a lot for your feedbacks ! 
There is a section in the doc explaining the "migration path", BUT if you did not see it, it means that we made a mistake somewhere ...What would be the best way to communicate this kind of info ? 
<img width="934" alt="Capture d’écran 2023-09-28 à 11 52 57" src="https://github.com/enix/kube-image-keeper/assets/6796335/be7b2263-ddd3-4717-a26c-4be2c3f7faac">

**Comment by guy-frontegg** [comment]
Thank you for your answer, you are absolutely correct and we just saw the upgrade section.
If I could just suggest bumping the Upgrade section to be higher in the readme section.
