### ISSUE TITLE
Cache failed for private Harbor registry

### ISSUE THREAD

**Issue by mceronja** [enix/kube-image-keeper#189]
Hi,

I installed latest (1.3.0) kube-image-keeper Helm chart with basically default values.yaml except I added my own expressions for the webhook selector.
I tested the [example ](https://github.com/enix/kube-image-keeper/blob/main/examples/deployment.yaml) from the repository and everything works fine. The images from docker and quay are said to be cached.

But for the deployments that use images from my private Harbor image registry, let's call it https://harbor.a.b.c things are not working. My deployments use `imagePullSecrets` to pull images from there.

From the events I see things like this:
```
Warning  CacheFailed  16m (x12 over 16m)  cachedimage-controller  
Failed to cache image harbor.a.b.c/project/image:tag, reason: could not find source image

Warning  Failed           19m (x4 over 20m)   kubelet            
Failed to pull image "localhost:7439/harbor.a.b.c/project/image:tag": 
	rpc error: code = Unknown desc = failed to pull and unpack image "localhost:7439/harbor.a.b.c/project/image:tag": 
	failed to resolve reference "localhost:7439/harbor.a.b.c/project/image:tag": 
	pulling from host localhost:7439 failed with status code [manifests tag]: 401 Unauthorized
```

and regarding kube-image-keeper logs I see things like this:
```
controller:
2023-10-06T12:30:07.109Z        ERROR   controller.cachedimage  Reconciler error        
{"reconciler group": "kuik.enix.io", "reconciler kind": "CachedImage", "name": "harbor.a.b.c/project/image:tag", 
"namespace": "", "error": "could not find source image"}

proxy:
Error #01: Get "https://harbor.a.b.c/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

In the Helm chart I don't see any special options regarding private registries, certificates, secrets, etc.
What should I do and is this supported?
Also if you need more information please say so.

Thanks in advance!

**Comment by paullaffitte** [comment]
Hello,

We added two ways to solve you issue:

- By using `insecureRegistries` value in the helm chart to define a list of allowed insecure registries (list of domain names). Here for instance you could use `insecureRegistries: ["harbor.a.b.c"]`.
- By using `rootCertificateAuthorities` value in the helm chart to reference a secret and keys in this secret containing root certificate authorities to trust. Here for instance you could use:

```yaml
rootCertificateAuthorities:
  secretName: my-secret
  keys: ["harborRootCA"]
```

**Comment by mceronja** [comment]
Hi @paullaffitte,

thanks I will test it out. I guess it will be in `v1.5.0` as the stable one.

BR
