### ISSUE TITLE
Port numbers in URLs break image caching

### ISSUE THREAD

**Issue by mccullough-ea** [enix/kube-image-keeper#191]
Hi,
We're having problems with a private repo that has an unusual port number, kube-image-keeper seems to mistake the port numbers as part of the hostname and fails to resolve it. 

Otherwise Kube Image cacher is working great for public repos and private repos with hostnames without ports.

Our internal repo is on port 5050 but most of the time we get something like this (I've changed the name of the repo for privacy but the real name has the same number of dots and only letters):

`cachedimage-controller:  Start caching image gitlab.dev.local-5050/devops/internal-wiki:main`
`cachedimage-controller: Failed to cache image gitlab.dev.local-5050/devops/internal-wiki:main, reason: Get "https://gitlab.dev.local-5050/v2/": dial tcp: lookup gitlab.dev.local-5050 on 172.20.0.10:53: no such host; Get "http://gitlab.dev.local-5050/v2/": dial tcp: lookup gitlab.dev.local-5050 on 172.20.0.10:53: no such host`

Unfortunately changing the port number isn't currently an option so it would be great for it to work on arbitrary ports.

Thanks,
Mike

**Comment by paullaffitte** [comment]
Hello, what version of kuik are you using ?

**Comment by mccullough-ea** [comment]
We're using the helm chart kube-image-keeper-1.2.0

**Comment by mccullough-ea** [comment]
Yes! 1.3.0 does not suffer from this behaviour! Thanks for the hint :+1:

**Comment by paullaffitte** [comment]
You're welcome :)
