### ISSUE TITLE
Please modify controller deployment manifest to set proxy variables

### ISSUE THREAD

**Issue by abbas916990** [enix/kube-image-keeper#192]
I am currently installing and testing kube-image-keeper in my corporate environment, and my Kubernetes cluster VMs are hosted behind a proxy. I've attempted to add environment variables for http_proxy , https_proxy and no_proxy  in the controller deployment, but it doesn't seem to be taking effect.

Could you please provide additional information? In cases where the image is not available in the local registry, which component is responsible for pulling the image from an upstream registry and pushing it to the local registry? If the controllers are responsible for this task, how can I incorporate the proxy variables into the respective controller pods?

I tried to edit controller manifest but it crashes with below error

2023/10/17 10:19:12 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota                                                                            │
│ 2023-10-17T10:19:22.373Z    ERROR    Failed to get API Group-Resources    {"error": "Get \"https://10.43.0.1:443/api?timeout=32s\": net/http: TLS handsha │
│ 2023-10-17T10:19:22.373Z    ERROR    setup    unable to start manager    {"error": "Get \"https://10.43.0.1:443/api?timeout=32s\": net/http: TLS handshake

**Comment by Nicolasgouze** [comment]
Hi @abbas916990 , Thanks for your feedback. We'll shortly double-check / have a look at this issue.

**Comment by abbas916990** [comment]
@Nicolasgouze could you please provide update on this

**Comment by Nicolasgouze** [comment]
Hello @abbas916990, 

I'll first answer your questions : 
- Both the controller AND proxy kuik components CAN pull images, 
- Adding environment variables into these components is the correct way to proceed.

On our end, we tested the scenario you depict, « playing » with environment variables and a squid proxy (outside of the cluster), and did not face this issue.
Anyway, we keep on investigating (adding logs on squid side and network policy to be 100% sure we use the proxy for outbound traffic)…. 

On your side, can you please elaborate a bit more on your test scenario : 
- Which proxy are you using ? 
- How did you update precisely the controller deployment ?
- I assume the provided log highlight a  controller —> proxy (—> API server) connexion. Is this traffic supposed to use the proxy ?

**Comment by abbas916990** [comment]
Which proxy are you using ?
Ans: We are using zscaler 
How did you update precisely the controller deployment ?
`--
# Source: kube-image-keeper/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-image-keeper-controllers
  labels:
    helm.sh/chart: kube-image-keeper-1.4.0
    app.kubernetes.io/name: kube-image-keeper
    app.kubernetes.io/instance: kube-image-keeper
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controllers
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-image-keeper
      app.kubernetes.io/instance: kube-image-keeper
      app.kubernetes.io/component: controllers
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-image-keeper
        app.kubernetes.io/instance: kube-image-keeper
        app.kubernetes.io/component: controllers
        control-plane: controller-manager
    spec:
      serviceAccountName: kube-image-keeper-controllers
      securityContext:
        {}
      containers:
        - name: cache-manager
          securityContext:
            {}
          image: "enix/kube-image-keeper:1.4.0"
          imagePullPolicy: IfNotPresent
          command:
            - manager
            - -leader-elect
            - -expiry-delay=30
            - -proxy-port=7439
            - -registry-endpoint=kube-image-keeper-registry:5000
            - -max-concurrent-cached-image-reconciles=3
            - -zap-log-level=INFO
            - -arch=amd64
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: http_proxy
              value: "http://web-proxy:8080"
            - name: https_proxy
              value: "http://web-proxy:8080"
            - name: no_proxy
              value: "localhost,127.0.0.1"              
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: kube-image-keeper-webhook-server-cert`
I assume the provided log highlight a controller —> proxy (—> API server) connexion. Is this traffic supposed to use the proxy

Answer: this is not a required connection. I provided the controller error message.

required connection is controller->proxy->origin registry if images are not present on cached images.
