### ISSUE TITLE
README.md points to the wrong helm chart location

### ISSUE THREAD

**Issue by baurmatt** [enix/kube-image-keeper#198]
Thanks for this project, it looks really promising. One thing I've noticed while evaluating it, is the wrong location of the Helm chart referenced in the README.md:

https://github.com/enix/kube-image-keeper/blob/54af3ff747a36795c248f7d9234a36bb72fca3fe/README.md?plain=1#L138C1-L138C106

**Comment by donch** [comment]
Hi @baurmatt , thanks for your positive feedback.

All our public charts are hosted at https://charts.enix.io and there is no mistake in the readme.

```
❯ helm search repo kube-image-keeper
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
enix/kube-image-keeper	1.4.0        	1.4.0      	kuik is a container image caching system for Ku...

❯ helm repo list
NAME                           	URL
enix                           	https://charts.enix.io
```

Sorry if it's a little bit confusing

**Comment by baurmatt** [comment]
Thanks for your quick response. The link in the README.md points to https://github.com/enix/helm-charts :)

**Comment by donch** [comment]
That's right, the sources are located in the [kuik's repository](https://github.com/enix/kube-image-keeper) but only the released helmchart is located in our [public repo](https://github.com/enix/helm-charts/releases)

We'll discuss this internally to clarify this.

**Comment by donch** [comment]
Hi, we clarify the chart repository location in the README ;) 

Thanks.
