### ISSUE TITLE
Image caching fails when multiple imagePullSecrets for the same registry

### ISSUE THREAD

**Issue by jperville** [enix/kube-image-keeper#237]
Hello,

I found the following issue when evaluating kube-image-keeper 1.4.0 (and 1.5.0-beta.1):
 - if a cachedimage has multiple imagePullSecrets for the same registry, only the first imagePullsSecret is tried and the image may fail to be pull, even if another imagePullSecret contains working credentials.

Let me give some context.
At our organization we host our docker images on the gitlab.com managed registry.

The structure of our organization docker registry looks like this:

```
$ tree 
.
└── registry.gitlab.com
    └── myorganization
        ├── clients
        │   ├── myclient1
        │   ├── myclient2
        │   └── myclient3
        └── platform
            └── docker

8 directories, 0 files
```

To prevent myclient2 from accessing the docker images from myclient1, we create group access tokens to give access to docker images hosted under each client, plus another group access token to give access to `myorganization/platform/docker` .
Those group access tokens are used in imagePullSecrets in the cluster.

Note : all these group access tokens use the same registry (registry.gitlab.com) but give access to different subsets of the registry.

Here is how the `default` service account look like on our cluster:

```
`$ kubectl get sa default -o yaml
apiVersion: v1
imagePullSecrets:
- name: docker-client-all     # this secret gives access to registry.gitlab.com/myorganization/clients/*
- name: docker-allinone      # and this one gives access to registry.gitlab.com/myorganization/platform/docker/*
kind: ServiceAccount
metadata:
  labels:
    name: default
  name: default
  namespace: applications
secrets:
- name: default-token-zzng2
```

Now the symptoms of the bug.

Kube-image-keeper v1.4.0 is installed on a kubernetes 1.26.6 cluster using the helm chart (slightly modified).

In the application namespaces:
 - all pods which have an image in `registry.gitlab.com/myorganization/platform/docker` are stuck in ImagePullBackoff
 - all pods which have an image in `registry.gitlab.com/myorganization/clients/myclient`  pull their image from the kuik registry and become Running

Here is how the `kubectl describe` of the broken cachedimage:

```
$ kubectl describe cachedimage registry.gitlab.com-myorganization-platform-docker-myapp-2.2.2
Name:         registry.gitlab.com-myorganization-platform-docker-myapp-2.2.2
Namespace:    
Labels:       kuik.enix.io/repository=registry.gitlab.com-myorganization-platform-docker-myapp
Annotations:  <none>
API Version:  kuik.enix.io/v1alpha1
Kind:         CachedImage
Metadata:
  Creation Timestamp:  2023-12-19T14:42:32Z
  Finalizers:
    cachedimage.kuik.enix.io/finalizer
  .... # snip
  Resource Version:  120137242
  UID:               07b31cca-715f-45a9-8055-ef5eb7859ecb
Spec:
  Pull Secret Names:
    docker-client-all
    docker-allinone
  Pull Secrets Namespace:  applications
  Source Image:            registry.gitlab.com/myorganization/platform/docker/myapp:2.2.2
Status:
  Used By:
    Count:  1
    Pods:
      Namespaced Name:  applications/myapp-68dc7944b9-pt4wv
Events:
  Type     Reason       Age                  From                    Message
  ----     ------       ----                 ----                    -------
  Warning  CacheFailed  11m (x12 over 12m)   cachedimage-controller  Failed to cache image registry.gitlab.com/myorganization/platform/docker/myapp:2.2.2, reason: GET https://registry.gitlab.com/v2/myorganization/platform/docker/myapp/manifests/2.2.2: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:myorganization/platform/docker/myapp ProjectPath: Type:repository]]
  Normal   Caching      2m7s (x22 over 12m)  cachedimage-controller  Start caching image registry.gitlab.com/myorganization/platform/docker/myapp:2.2.2
```

My theory is that the controller tried to pull the docker image using the first imagePullSecret (docker-client-all) and gave up. If the controller had fall back to trying the second imagePullSecret (docker-allinone) then it could have cached the image successfully.

If I manually edit the cachedimage to remove the first imagePullSecret (docker-client-all) then kuik successfully pulls the docker image and the myapp pods become Running.

**Comment by paullaffitte** [comment]
Hello,

You guessed right, we only try the first imagePullSecret (that match the domain of your image), but I think it will not be trivial to fix it. Indeed we use the [authn.NewMultiKeychain](https://github.com/google/go-containerregistry/blob/main/pkg/authn/multikeychain.go) function from https://github.com/google/go-containerregistry to handle authentication using multiple pull secrets, and the way it works is by iterating over all the pull secrets that we gave to it and return the first that match the domain of the image. Implementing a retry mechanism would be a tedious task.

I could inspect the code of kubelet to find how they handle that in a classic (without kuik) pull scenario, but I would like to be sure that kubelet itself knows how to handle this case before doing so. Could you confirm that without kuik, kubelet is able to pull the image `registry.gitlab.com/myorganization/platform/docker/myapp:2.2.2` even when your default service account contains both imagePullSecrets please ?

In the case it doesn't, the solution could be to only use the right imagePullSecrets for the corresponding images.

**Comment by jperville** [comment]
Yes @paullaffitte , we never had problem to pull our docker images before kuik.

**Comment by paullaffitte** [comment]
OK so it seems that kubelet takes another approach that is trying each secrets one by one until one works (see [kuberuntime_image.go#L35](https://github.com/kubernetes/kubernetes/blob/v1.29.0/pkg/kubelet/kuberuntime/kuberuntime_image.go#L35)). I can try to reproduce this behavior.

**Comment by jperville** [comment]
Yes, I checked the issue tracker on https://github.com/google/go-containerregistry and I found multiple bug reports and incomplete pull requests attempting to solve the problem. Still no solution there but kubernetes code may work.
