### ISSUE TITLE
Consider publishing images to Quay or GHCR

### ISSUE THREAD

**Issue by onedr0p** [enix/kube-image-keeper#24]
Hi 👋🏼 

It would be great if the images were on a other container registry other than dockerhub.

Thanks!

**Comment by donch** [comment]
Hi @onedr0p , thanks for your interest !
We already push images to DockerHub and Quay (https://quay.io/repository/enix/kube-image-keeper)

We'll enhance the documentation to mention it !

**Comment by onedr0p** [comment]
Personally I would make quay the default in the helm chart :)
