### ISSUE TITLE
Intermittent Failed to pull image

### ISSUE THREAD

**Issue by ppapp92** [enix/kube-image-keeper#247]
I'm trying to deploy kube image keeper in AWS EKS using a Standalone Minio installation.

I had no issue getting it configured and the registry is able to connect and store images in Minio. However some of the EKS node, at what seems to be random fail to be able to pull images from the registry with the following error.

```Failed to pull image "localhost:7439/docker.io/grafana/promtail:2.7.4": failed to pull and unpack image "localhost:7439/docker.io/grafana/promtail:2.7.4": failed to copy: httpReadSeeker: failed open: failed to do request: Get "http://minio.minio.svc.cluster.local:9000/registry/docker/registry/v2/blobs/sha256/78/78e4198d60e924f58ae4e9dbcf647dfe0fc72eb594fba3a9f0f35b98eeb3a759/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx%2F20240112%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240112T191123Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=341bf92fdbf7d9ccf87859afbb419c4f407527ea8222228fd2ea8f8ae0d4e64e": dial tcp: lookup minio.minio.svc.cluster.local: no such host```

Some nodes are able to pull the same image without any issues and the networking setup of all the nodes are the same. I've verified that the node is able to access the service.

If I used the out-of-the-box Minio implementation everything seems to work fine and the only difference seems to be that Minio is in it's own namespace.

**Comment by ppapp92** [comment]
Just to add to this. I've created this same setup but with MinIO with public ingress and that seems to work properly. But still seems to be an issue with connecting to the MinIO service.

**Comment by paullaffitte** [comment]
Hello,

What version of kuik do you use? Could you show me the values that you used to install the chart please?

By default, the registry is accessed via `http://kube-image-keeper-minio:9000`, did you configured the value `.Values.minio.fullnameOverride` to `minio.minio.svc.cluster.local`? Could you try to run `nslookup minio.minio.svc.cluster.local` from different nodes and confirm that some nodes only can resolve this domain name?
