### ISSUE TITLE
No configured node selector, and on windows node support

### ISSUE THREAD

**Issue by rolfbartels** [enix/kube-image-keeper#315]
The deployment seems to not have a configured node selector and when deploying to a hybrid cluster, one with both Linux nad windows nodes the image fails on the windows nodes.

**Comment by Nicolasgouze** [comment]
Hi @rolfbartels, 

A couple of feedbacks : 
- We DO have node selectors implemented for both the registry AND internally developped kuik components. You have to update following keys before deploying : controller.nodeSelector for, proxy.nodeSelector, registry.nodeSelector. 
- kuik is not tested with windows worker nodes (and we do not plan to implement this feature atm) so we do not ensure it will work in your scenario. I assume the goal for your previous question was to install kuik only on linux nodes, right ? 

I'm thus closing this ticket.
