### ISSUE TITLE
Registry Pod OOMKilled

### ISSUE THREAD

**Issue by sukumardandu** [enix/kube-image-keeper#378]
Registry pod is constantly getting OOMKilled with varied time intervals. Least is under 60 min, best is between 6-7 hours

There are no details or errors in the container logs.

For Memory we started with 1GB and started to increase by 1 GB and now we are at 7GB and still the registry pod is continuously being OOMKIlled

I am currently running 1.4.0 version and for registry we are using image: registry:2.8.2

Please let me know if you need additional details

**Comment by paullaffitte** [comment]
Hello, thanks for your reaching us.

Our team does not develop or maintain the registry component, so I would suggest that you post your issue on the dedicated repository instead (https://github.com/distribution/distribution).

I'm closing the issue, but feel free to re-open it if you consider that it comes from the way we configured the registry. And please link this issue to the new one on the other repository so it will be easier to follow-up.
