### ISSUE TITLE
Add global ImagePullSecret

### ISSUE THREAD

**Issue by D2NM0** [enix/kube-image-keeper#385]
We are thinking of installing kuik on our GCP clusters. we have 100+ microservices that are using images from GCP artifact registry, and GKE does not need the ImagePullSecret to access artifact registry. It would be better to add an option of a global ImagePullSecret in the values file instead of adding it to each microservice

**Comment by paullaffitte** [comment]
Hello,

We already have an issue about it : #267

We will try to implement automatic retrieval of pull secrets first, using global ImagePullSecrets will be considered only if we fail implementing it.

I'm thus closing this issue for now.

**Comment by paullaffitte** [comment]
For the posterity : we did it ! #428
