### ISSUE TITLE
Kubernetes 1.30 ?

### ISSUE THREAD

**Issue by billnbell3** [enix/kube-image-keeper#409]
Is this tested on Kube 1.30 clusters on EKS AWS ?

**Comment by Nicolasgouze** [comment]
Hi @billnbell3, 
Short answer : no. 
We use kuik on "real life" clusters, using 1.24 to 1.28 k8s versions.
Our internal github install & tests processes cover 1.24 to 1.29 k8s versions. 
We should shortly officially support 1.30.

**Comment by didlawowo** [comment]
it's working on k3S 1.30 since  two weeks in my side

**Comment by Nicolasgouze** [comment]
We're now supporting the 1.30. Closing this ticket.
