### ISSUE TITLE
no arm64 proxy image

### ISSUE THREAD

**Issue by zig** [enix/kube-image-keeper#67]
When using this project in a cluster with arm64 nodes, the kube-image-keeper-proxy pods fail to run on these nodes (wrong exec format). 

This would require to build a muti arch image.

PS: awesome project nevertheless !

**Comment by donch** [comment]
Hi @zig , we'll test it on arm64 nodes, but we use multi arch build for our image : https://hub.docker.com/layers/enix/kube-image-keeper/1.0.1/images/sha256-590b07b71fe93e2e1fae99dd0fb3d4c1e44f1b1864a99ba6c02f43ff009789d5?context=explore

We'll keep you posted !

**Comment by zig** [comment]
Sorry for the confusion, I assumed they were not multi arch because of the error I was getting ! 

I suspect the arm64 image contains  amd64 code (a hint is that the images have exactly the same size). 

I did a build on my side, using `docker buildx`, and it is working.

**Comment by Nicolasgouze** [comment]
Hi @zig, we're about to release a beta version that will fix the arm64 build issue & promote it to a standard release once our tests are fine !

**Comment by donch** [comment]
Hi @zig , a beta version is available (https://github.com/enix/kube-image-keeper/releases/tag/v1.1.0-beta.1) with the associated helm-chart and images (for amd64 & arm64)
