### ISSUE TITLE
Pull pod docker images with an ECR one in it.

### ISSUE THREAD

**Issue by bunnybilou** [enix/kube-image-keeper#82]
Hi guys,

I would like to use kuik to cache some linkerd proxy container sidecar public images `cr.l5d.io/linkerd/proxy`. But the image of our APP is hosted on ECR and I have a 401 when the controller is trying to pull from it. 

Caching ECR images in kuik doesn't really matters to me the only thing I want is to pull linkerd images from the kuik cache. 

Do you have any idea on how I can only fetch some pod images and not the others ?

**Comment by bunnybilou** [comment]
What I understand from [pod-filtering](https://github.com/enix/kube-image-keeper#pod-filtering) is that you can filter pods not containers inside a pod so in my case it won't work.

**Comment by donch** [comment]
Hi @bunnybilou , even if you are discussing internally to propose the ability to target specific containers in kuik,  this [feature](https://github.com/enix/kube-image-keeper/commit/79c2a36b8fca2a6b2f166c14a83066d345446837) may helps you ?

**Comment by Nicolasgouze** [comment]
Hi @bunnybilou, I'm closing this issue (because we now support ECR, even though we know we have a bug we're working on ... ). We're in // working on the "container level filtering : https://github.com/enix/kube-image-keeper/pull/132. I propose you to follow this PR !

**Comment by Nicolasgouze** [comment]
Hi @bunnybilou, I'm closing this issue (because we now support ECR, even though we know we have a bug we're working on ... ). We're in // working on the "container level filtering : https://github.com/enix/kube-image-keeper/pull/132. I propose you to follow this PR !
