### ISSUE TITLE
ImagePullSecret discovery : Wilcard never match

### ISSUE THREAD

**Issue by cdesaintleger** [enix/kube-image-keeper#92]
Using private registry, ex xxx.jfrog.io
The secret used to pull images from this repos is formated as below

`.dockerconfigjson: '{"auths": {"*.jfrog.io": {"username":"mylogin","password":"xxx","email":"foo@bar"}}}'`

the wildcard not seems to be used to discover the correct credential to use. 

If a change the wildcard by the complete registry hostname ex : demo-api.jfrog.io, all works fine.

**Comment by Nicolasgouze** [comment]
Hi @cdesaintleger, 
Happy you’re using kuik ! 
With this project, we re-use **as is** the docker code (https://github.com/docker/cli/tree/master/cli/config), responsible for the behavior you face / do not want to override such code.
